name: "bumper"

on:
  workflow_dispatch:
    inputs:
      version:
        description: How to bump package version
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x

      - name: NPM Bump
        id: bump
        run: |
          git config user.email 'github-actions[bot]@users.noreply.github.com"'
          git config user.name 'github-actions[bot]'
          npm version ${{ inputs.version }}
          echo "version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bumper/${{ steps.bump.outputs.version }}
          delete-branch: true
          title: Bump ${{ inputs.version }} version to ${{ steps.bump.outputs.version }}
          body: "created by `bump` workflow manually run by ${{ github.actor }}"

      - name: Set PR auto-merge
        run: gh pr merge --auto --rebase "${{ steps.create-pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ github.token }}
