name: "bumper"

on:
  push:
    branches: [ main ]

jobs:
  load-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract PR
        uses: ./
        id: pr

    outputs:
      is-pr: ${{ steps.pr.outputs.pr != 'false' }}
      version-bump: ${{ contains(fromJson(steps.pr.outputs.pr).labels.*.name, 'bump:patch') && 'patch' || (contains(fromJson(steps.pr.outputs.pr).labels.*.name, 'bump:minor') && 'minor' || (contains(fromJson(steps.pr.outputs.pr).labels.*.name, 'bump:major') && 'major' || 'unknown')) }}

  bump:
    runs-on: ubuntu-latest
    needs:
      - load-pr
    if: needs.load-pr.outputs.is-pr == 'true' && needs.load-pr.outputs.version-bump != 'unknown'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.x

      - name: NPM Bump
        run: |
          git config user.email 'bumper[bot]@users.noreply.github.com"'
          git config user.name 'bumper[bot]'
          npm version ${{ needs.load-pr.outputs.version-bump }}
          echo "version=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          tags: true

          